### PR TITLE
Update Kratos to 1.2.0

### PR DESCRIPTION
**Pull request by Saancreed**
Plus my OIDC patches. Passkeys and two step registration are still disabled for now.

### CODE REVIEW

**Comment by Dragemil** [comment]
What about updating client APIs?

**Review by jakubfijalkowski — APPROVED** [review]

**Comment by Saancreed** [comment]
> What about updating client APIs?

@Dragemil What about them?

**Comment by Dragemil** [comment]
Don't we want to include the updates of the client to this PR to guard against breaking changes which Szymon encountered?

**Comment by Saancreed** [comment]
I'll check again but I'm pretty sure we aren't using any API that had breaking changes in the meantime. We can afford to keep using the current client for now.

**Comment by Dragemil** [comment]
I'd say even if exampleapp-wise having a bit of kratos client and server version difference would be fine, but templateapp wise it is a bit of a trap, no?

**Comment by jakubfijalkowski** [comment]
Yes, in a long term, that would be bad. But we don't need to do everything at once. :)

**Review by Dragemil — APPROVED** [review]

**Comment by Saancreed** [comment]
I split the update into two commits, one for Kratos itself and another for reference UI and also added missing environment variables required by new version of reference UI.

**Pull request merged**
